### ISSUE TITLE
best on the market

### ISSUE THREAD

**Issue by 3jq** [WalmartSolutions/jvm-manual#2]
like im not even lying this is fucking gold

**Comment by ethaanol** [comment]
so true

**Comment by ethaanol** [comment]
this issue has been approved by the Islamic State of Iraq and Syria.

**Comment by 3jq** [comment]
> this issue has been approved by the Islamic State of Iraq and Syria.

NO IT WASNT

**Comment by ethaanol** [comment]
☠️
